export const LOAD_ECOMMERCE_INIT = "LOAD_ECOMMERCE_INIT";
export const LOAD_ECOMMERCE_SUCCEED = "LOAD_ECOMMERCE_SUCCEED";
export const LOAD_ECOMMERCE_FAILED = "LOAD_ECOMMERCE_FAILED";

export const ADD_PRODUCT = "ADD_PRODUCT";
